export const FETCH_NEW_HIGHLIGHT_DATA = 'FETCH_NEW_HIGHLIGHT_DATA';
export const FETCH_NEW_HIGHLIGHT_DATA_SUCCESS = 'FETCH_NEW_HIGHLIGHT_DATA_SUCCESS';
export const FETCH_NEW_HIGHLIGHT_DATA_ERROR = 'FETCH_NEW_HIGHLIGHT_DATA_ERROR';